flags: {}
packages:
- todobackend-common
- todobackend-happstack
- todobackend-scotty
- todobackend-servant
- todobackend-snap
- todobackend-spock
- todobackend-yesod
extra-deps:
- heist-1.0.1.0
- snap-1.0.0.2
- snap-core-1.0.3.1
- snap-server-1.0.3.3
- xmlhtml-0.2.5.1
- map-syntax-0.2.0.2
resolver: lts-9.21
