flags: {}
packages:
- todobackend-common
- todobackend-scotty
- todobackend-servant
- todobackend-snap
- todobackend-spock
- todobackend-yesod
extra-deps:
- snap-extras-0.11.0.1
- digestive-functors-heist-0.8.6.2
- digestive-functors-snap-0.6.1.3
- readable-0.3.1
resolver: nightly-2015-07-28
