flags: {}
packages:
- todobackend-common
- todobackend-happstack
- todobackend-scotty
- todobackend-servant
- todobackend-snap
- todobackend-spock
- todobackend-yesod
extra-deps:
- heist-1.1
- snap-1.1.1.0
- snap-core-1.0.3.2
- snap-server-1.1.0.0
- xmlhtml-0.2.5.2
- map-syntax-0.3
- pwstore-fast-2.4.4
resolver: lts-12.14
